package edu.health.dao;

import edu.health.model.CmtWithBLOBs;
import org.apache.ibatis.jdbc.SQL;

public class CmtSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public String insertSelective(CmtWithBLOBs record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("cmt");
		if (record.getCmtId() != null) {
			sql.VALUES("cmt_id", "#{cmtId,jdbcType=INTEGER}");
		}
		if (record.getUserId() != null) {
			sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
		}
		if (record.getTopicId() != null) {
			sql.VALUES("topic_id", "#{topicId,jdbcType=INTEGER}");
		}
		if (record.getContent() != null) {
			sql.VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
		}
		if (record.getRepeat() != null) {
			sql.VALUES("repeat", "#{repeat,jdbcType=LONGVARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public String updateByPrimaryKeySelective(CmtWithBLOBs record) {
		SQL sql = new SQL();
		sql.UPDATE("cmt");
		if (record.getUserId() != null) {
			sql.SET("user_id = #{userId,jdbcType=INTEGER}");
		}
		if (record.getTopicId() != null) {
			sql.SET("topic_id = #{topicId,jdbcType=INTEGER}");
		}
		if (record.getContent() != null) {
			sql.SET("content = #{content,jdbcType=LONGVARCHAR}");
		}
		if (record.getRepeat() != null) {
			sql.SET("`repeat` = #{repeat,jdbcType=LONGVARCHAR}");
		}
		sql.WHERE("cmt_id = #{cmtId,jdbcType=INTEGER}");
		return sql.toString();
	}
}