package edu.health.dao;

import edu.health.model.Exam;
import org.apache.ibatis.jdbc.SQL;

public class ExamSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	public String insertSelective(Exam record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("exam");
		if (record.getExamId() != null) {
			sql.VALUES("exam_id", "#{examId,jdbcType=INTEGER}");
		}
		if (record.getExamName() != null) {
			sql.VALUES("exam_name", "#{examName,jdbcType=VARCHAR}");
		}
		if (record.getExamType() != null) {
			sql.VALUES("exam_type", "#{examType,jdbcType=INTEGER}");
		}
		if (record.getExamContent() != null) {
			sql.VALUES("exam_content", "#{examContent,jdbcType=LONGVARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	public String updateByPrimaryKeySelective(Exam record) {
		SQL sql = new SQL();
		sql.UPDATE("exam");
		if (record.getExamName() != null) {
			sql.SET("exam_name = #{examName,jdbcType=VARCHAR}");
		}
		if (record.getExamType() != null) {
			sql.SET("exam_type = #{examType,jdbcType=INTEGER}");
		}
		if (record.getExamContent() != null) {
			sql.SET("exam_content = #{examContent,jdbcType=LONGVARCHAR}");
		}
		sql.WHERE("exam_id = #{examId,jdbcType=INTEGER}");
		return sql.toString();
	}
}