package edu.health.dao;

import edu.health.model.Topic;
import org.apache.ibatis.jdbc.SQL;

public class TopicSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public String insertSelective(Topic record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("topic");
		if (record.getArticleId() != null) {
			sql.VALUES("article_id", "#{articleId,jdbcType=INTEGER}");
		}
		if (record.getTitle() != null) {
			sql.VALUES("title", "#{title,jdbcType=VARCHAR}");
		}
		if (record.getUserId() != null) {
			sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
		}
		if (record.getCreateDate() != null) {
			sql.VALUES("create_date", "#{createDate,jdbcType=TIMESTAMP}");
		}
		if (record.getContent() != null) {
			sql.VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public String updateByPrimaryKeySelective(Topic record) {
		SQL sql = new SQL();
		sql.UPDATE("topic");
		if (record.getTitle() != null) {
			sql.SET("title = #{title,jdbcType=VARCHAR}");
		}
		if (record.getUserId() != null) {
			sql.SET("user_id = #{userId,jdbcType=INTEGER}");
		}
		if (record.getCreateDate() != null) {
			sql.SET("create_date = #{createDate,jdbcType=TIMESTAMP}");
		}
		if (record.getContent() != null) {
			sql.SET("content = #{content,jdbcType=LONGVARCHAR}");
		}
		sql.WHERE("article_id = #{articleId,jdbcType=INTEGER}");
		return sql.toString();
	}
}