package edu.health.dao;

import edu.health.model.UserExamWithBLOBs;
import org.apache.ibatis.jdbc.SQL;

public class UserExamSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    public String insertSelective(UserExamWithBLOBs record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user_exam");
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getExamId() != null) {
            sql.VALUES("exam_id", "#{examId,jdbcType=INTEGER}");
        }
        
        if (record.getDoctorId() != null) {
            sql.VALUES("doctor_id", "#{doctorId,jdbcType=INTEGER}");
        }
        
        if (record.getAnswer() != null) {
            sql.VALUES("answer", "#{answer,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getAdvice() != null) {
            sql.VALUES("advice", "#{advice,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    public String updateByPrimaryKeySelective(UserExamWithBLOBs record) {
        SQL sql = new SQL();
        sql.UPDATE("user_exam");
        
        if (record.getDoctorId() != null) {
            sql.SET("doctor_id = #{doctorId,jdbcType=INTEGER}");
        }
        
        if (record.getAnswer() != null) {
            sql.SET("answer = #{answer,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getAdvice() != null) {
            sql.SET("advice = #{advice,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("user_id = #{userId,jdbcType=INTEGER}");
        sql.WHERE("exam_id = #{examId,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}