package edu.health.dao;

import edu.health.model.Users;
import org.apache.ibatis.jdbc.SQL;

public class UsersSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public String insertSelective(Users record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("users");
		if (record.getUserId() != null) {
			sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
		}
		if (record.getLoginName() != null) {
			sql.VALUES("login_name", "#{loginName,jdbcType=VARCHAR}");
		}
		if (record.getLoginPwd() != null) {
			sql.VALUES("login_pwd", "#{loginPwd,jdbcType=VARCHAR}");
		}
		if (record.getUserType() != null) {
			sql.VALUES("user_type", "#{userType,jdbcType=INTEGER}");
		}
		if (record.getState() != null) {
			sql.VALUES("state", "#{state,jdbcType=SMALLINT}");
		}
		if (record.getTel() != null) {
			sql.VALUES("tel", "#{tel,jdbcType=VARCHAR}");
		}
		if (record.getEmail() != null) {
			sql.VALUES("email", "#{email,jdbcType=VARCHAR}");
		}
		if (record.getAvatar() != null) {
			sql.VALUES("avatar", "#{avatar,jdbcType=VARCHAR}");
		}
		if (record.getSchool() != null) {
			sql.VALUES("school", "#{school,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public String updateByPrimaryKeySelective(Users record) {
		SQL sql = new SQL();
		sql.UPDATE("users");
		if (record.getLoginName() != null) {
			sql.SET("login_name = #{loginName,jdbcType=VARCHAR}");
		}
		if (record.getLoginPwd() != null) {
			sql.SET("login_pwd = #{loginPwd,jdbcType=VARCHAR}");
		}
		if (record.getUserType() != null) {
			sql.SET("user_type = #{userType,jdbcType=INTEGER}");
		}
		if (record.getState() != null) {
			sql.SET("state = #{state,jdbcType=SMALLINT}");
		}
		if (record.getTel() != null) {
			sql.SET("tel = #{tel,jdbcType=VARCHAR}");
		}
		if (record.getEmail() != null) {
			sql.SET("email = #{email,jdbcType=VARCHAR}");
		}
		if (record.getAvatar() != null) {
			sql.SET("avatar = #{avatar,jdbcType=VARCHAR}");
		}
		if (record.getSchool() != null) {
			sql.SET("school = #{school,jdbcType=VARCHAR}");
		}
		sql.WHERE("user_id = #{userId,jdbcType=INTEGER}");
		return sql.toString();
	}
}