package edu.health.model;

public class Cmt {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt.cmt_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	private Integer cmtId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt.user_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt.topic_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	private Integer topicId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt.cmt_id
	 * @return  the value of cmt.cmt_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public Integer getCmtId() {
		return cmtId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt.cmt_id
	 * @param cmtId  the value for cmt.cmt_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public void setCmtId(Integer cmtId) {
		this.cmtId = cmtId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt.user_id
	 * @return  the value of cmt.user_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt.user_id
	 * @param userId  the value for cmt.user_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt.topic_id
	 * @return  the value of cmt.topic_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public Integer getTopicId() {
		return topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt.topic_id
	 * @param topicId  the value for cmt.topic_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}
}