package edu.health.model;

public class CmtWithBLOBs extends Cmt {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt.content
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt.repeat
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	private String repeat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt.content
	 * @return  the value of cmt.content
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt.content
	 * @param content  the value for cmt.content
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt.repeat
	 * @return  the value of cmt.repeat
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public String getRepeat() {
		return repeat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt.repeat
	 * @param repeat  the value for cmt.repeat
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public void setRepeat(String repeat) {
		this.repeat = repeat == null ? null : repeat.trim();
	}
}