package edu.health.model;

public class Exam {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exam.exam_id
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	private Integer examId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exam.exam_name
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	private String examName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exam.exam_type
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	private Integer examType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exam.exam_content
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	private String examContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exam.exam_id
	 * @return  the value of exam.exam_id
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	public Integer getExamId() {
		return examId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exam.exam_id
	 * @param examId  the value for exam.exam_id
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exam.exam_name
	 * @return  the value of exam.exam_name
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	public String getExamName() {
		return examName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exam.exam_name
	 * @param examName  the value for exam.exam_name
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	public void setExamName(String examName) {
		this.examName = examName == null ? null : examName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exam.exam_type
	 * @return  the value of exam.exam_type
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	public Integer getExamType() {
		return examType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exam.exam_type
	 * @param examType  the value for exam.exam_type
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	public void setExamType(Integer examType) {
		this.examType = examType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exam.exam_content
	 * @return  the value of exam.exam_content
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	public String getExamContent() {
		return examContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exam.exam_content
	 * @param examContent  the value for exam.exam_content
	 * @mbg.generated  Wed Jan 15 11:10:10 CST 2020
	 */
	public void setExamContent(String examContent) {
		this.examContent = examContent == null ? null : examContent.trim();
	}

	@Override
	public String toString() {
		return "Exam [examId=" + examId + ", examName=" + examName + ", examType=" + examType + ", examContent="
				+ examContent + "]";
	}
	
	
}