package edu.health.model;

import java.math.BigDecimal;

public class PhysicalExam {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.test_id
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private Integer testId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.height
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private BigDecimal height;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.weight
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private BigDecimal weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.heartbeat
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private String heartbeat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.vital_capacity
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private BigDecimal vitalCapacity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.sex
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.stu_id
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private Integer stuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.doctor_id
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private Integer doctorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.left_eye
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private String leftEye;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.right_eye
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private String rightEye;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.hearing
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private String hearing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column physical_exam.advice
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	private String advice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.test_id
	 * @return  the value of physical_exam.test_id
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public Integer getTestId() {
		return testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.test_id
	 * @param testId  the value for physical_exam.test_id
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.height
	 * @return  the value of physical_exam.height
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public BigDecimal getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.height
	 * @param height  the value for physical_exam.height
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.weight
	 * @return  the value of physical_exam.weight
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public BigDecimal getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.weight
	 * @param weight  the value for physical_exam.weight
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.heartbeat
	 * @return  the value of physical_exam.heartbeat
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public String getHeartbeat() {
		return heartbeat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.heartbeat
	 * @param heartbeat  the value for physical_exam.heartbeat
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setHeartbeat(String heartbeat) {
		this.heartbeat = heartbeat == null ? null : heartbeat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.vital_capacity
	 * @return  the value of physical_exam.vital_capacity
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public BigDecimal getVitalCapacity() {
		return vitalCapacity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.vital_capacity
	 * @param vitalCapacity  the value for physical_exam.vital_capacity
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setVitalCapacity(BigDecimal vitalCapacity) {
		this.vitalCapacity = vitalCapacity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.sex
	 * @return  the value of physical_exam.sex
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.sex
	 * @param sex  the value for physical_exam.sex
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.stu_id
	 * @return  the value of physical_exam.stu_id
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public Integer getStuId() {
		return stuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.stu_id
	 * @param stuId  the value for physical_exam.stu_id
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.doctor_id
	 * @return  the value of physical_exam.doctor_id
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public Integer getDoctorId() {
		return doctorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.doctor_id
	 * @param doctorId  the value for physical_exam.doctor_id
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.left_eye
	 * @return  the value of physical_exam.left_eye
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public String getLeftEye() {
		return leftEye;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.left_eye
	 * @param leftEye  the value for physical_exam.left_eye
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setLeftEye(String leftEye) {
		this.leftEye = leftEye == null ? null : leftEye.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.right_eye
	 * @return  the value of physical_exam.right_eye
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public String getRightEye() {
		return rightEye;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.right_eye
	 * @param rightEye  the value for physical_exam.right_eye
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setRightEye(String rightEye) {
		this.rightEye = rightEye == null ? null : rightEye.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.hearing
	 * @return  the value of physical_exam.hearing
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public String getHearing() {
		return hearing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.hearing
	 * @param hearing  the value for physical_exam.hearing
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setHearing(String hearing) {
		this.hearing = hearing == null ? null : hearing.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column physical_exam.advice
	 * @return  the value of physical_exam.advice
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public String getAdvice() {
		return advice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column physical_exam.advice
	 * @param advice  the value for physical_exam.advice
	 * @mbg.generated  Thu Feb 27 11:23:34 CST 2020
	 */
	public void setAdvice(String advice) {
		this.advice = advice == null ? null : advice.trim();
	}

	@Override
	public String toString() {
		return "PhysicalExam [testId=" + testId + ", height=" + height + ", weight=" + weight + ", heartbeat="
				+ heartbeat + ", vitalCapacity=" + vitalCapacity + ", sex=" + sex + ", stuId=" + stuId + ", doctorId="
				+ doctorId + "]";
	}
    
    
}