package edu.health.model;

import java.util.Date;

public class Topic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.article_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	private Integer articleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.title
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.user_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.create_date
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.content
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.article_id
	 * @return  the value of topic.article_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public Integer getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.article_id
	 * @param articleId  the value for topic.article_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.title
	 * @return  the value of topic.title
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.title
	 * @param title  the value for topic.title
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.user_id
	 * @return  the value of topic.user_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.user_id
	 * @param userId  the value for topic.user_id
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.create_date
	 * @return  the value of topic.create_date
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.create_date
	 * @param createDate  the value for topic.create_date
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.content
	 * @return  the value of topic.content
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.content
	 * @param content  the value for topic.content
	 * @mbg.generated  Tue Jan 14 13:01:07 CST 2020
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}