package edu.health.model;

public class UserExamWithBLOBs extends UserExam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam.answer
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam.advice
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    private String advice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam.answer
     *
     * @return the value of user_exam.answer
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam.answer
     *
     * @param answer the value for user_exam.answer
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam.advice
     *
     * @return the value of user_exam.advice
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam.advice
     *
     * @param advice the value for user_exam.advice
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    public void setAdvice(String advice) {
        this.advice = advice == null ? null : advice.trim();
    }
}