package edu.health.model;

public class UserExam extends UserExamKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam.doctor_id
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    private Integer doctorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam.doctor_id
     *
     * @return the value of user_exam.doctor_id
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam.doctor_id
     *
     * @param doctorId the value for user_exam.doctor_id
     *
     * @mbg.generated Tue Jan 14 12:40:34 CST 2020
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }
}