package edu.health.model;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.user_id
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.login_name
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.login_pwd
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	private String loginPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.user_type
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	private Integer userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.state
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	private Short state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.tel
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.email
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.avatar
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	private String avatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.school
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	private String school;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.user_id
	 * @return  the value of users.user_id
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.user_id
	 * @param userId  the value for users.user_id
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.login_name
	 * @return  the value of users.login_name
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.login_name
	 * @param loginName  the value for users.login_name
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName == null ? null : loginName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.login_pwd
	 * @return  the value of users.login_pwd
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public String getLoginPwd() {
		return loginPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.login_pwd
	 * @param loginPwd  the value for users.login_pwd
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd == null ? null : loginPwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.user_type
	 * @return  the value of users.user_type
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public Integer getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.user_type
	 * @param userType  the value for users.user_type
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.state
	 * @return  the value of users.state
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public Short getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.state
	 * @param state  the value for users.state
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public void setState(Short state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.tel
	 * @return  the value of users.tel
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.tel
	 * @param tel  the value for users.tel
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.email
	 * @return  the value of users.email
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.email
	 * @param email  the value for users.email
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.avatar
	 * @return  the value of users.avatar
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.avatar
	 * @param avatar  the value for users.avatar
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar == null ? null : avatar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.school
	 * @return  the value of users.school
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.school
	 * @param school  the value for users.school
	 * @mbg.generated  Mon Mar 09 11:09:42 CST 2020
	 */
	public void setSchool(String school) {
		this.school = school == null ? null : school.trim();
	}

	@Override
	public String toString() {
		return "Users [userId=" + userId + ", loginName=" + loginName + ", loginPwd=" + loginPwd + ", userType="
				+ userType + ", state=" + state + ", tel=" + tel + ", email=" + email + ", avatar=" + avatar + "]";
	}
	
	
}